spring:
  application:
    name: springbootcompare
  session:
    store-type: redis
    redis:
      namespace: SPRING_SESSION
      flush-mode: on_save
  datasource:
    hikari:
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:tcp://localhost/~/test
#      password: sa
#      username: sa
      maximum-pool-size: 10
      minimum-idle: 2
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: h2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  redis:
    host: localhost
    port: 6379
    pool:
      max-wait: 10000
server:
  port: 9001
